-- Postgres extensions used across the schema.
-- The spike uses Postgres built-in full-text search (tsvector/tsquery) for
-- lca_knowledge, so no extension is required at the moment. Add new
-- extensions here when needed (e.g. `create extension if not exists vector`
-- for pgvector if we move to semantic search).
